#!/bin/bash

set -e

my_path=$(dirname "$0")

source "$my_path"/0vpn-options

echo Creating temporary file...
TMPFILE=$(mktemp) || exit 1

echo TMPFILE is "$TMPFILE"

TMPDIR=$(mktemp -d) || exit 1

echo TMPDIR is "$TMPDIR"

mkdir "$TMPDIR/hosts"
mkdir "$TMPDIR/configs"

chmod -R 755 "$TMPDIR"

trap 'kill $(cat "$TMPDIR/dnsmasq.pid"); rm -f "$TMPFILE"; rm -rf "$TMPDIR"' EXIT

root_wg_ip=$("$my_path"/0vpn-resolve "$ZEROVPN_SERVER_NAME")
echo root wg ip: "$root_wg_ip"

echo "$root_wg_ip" "$ZEROVPN_SERVER_NAME".internal > "$TMPDIR"/hosts/"$ZEROVPN_SERVER_NAME"

echo Setting up wireguard device "$ZEROVPN_WIREGUARD_DEVICE"...
echo Deleting device..."$(ip link delete "$ZEROVPN_WIREGUARD_DEVICE")"
ip link add "$ZEROVPN_WIREGUARD_DEVICE" type wireguard
ip addr add "$root_wg_ip" dev "$ZEROVPN_WIREGUARD_DEVICE"
ip addr add "$("$my_path"/0vpn-ipv6-address "$ZEROVPN_KEYFILE" "$ZEROVPN_SERVER_NAME")" dev "$ZEROVPN_WIREGUARD_DEVICE"
"$my_path"/0vpn-tool mixin "$ZEROVPN_KEYFILE" "$ZEROVPN_SERVER_NAME" > "$TMPFILE"

echo Root public key: "$(wg pubkey < "$TMPFILE")"

wg set "$ZEROVPN_WIREGUARD_DEVICE" private-key "$TMPFILE"
wg set "$ZEROVPN_WIREGUARD_DEVICE" listen-port "$ZEROVPN_WIREGUARD_PORT"
ip link set "$ZEROVPN_WIREGUARD_DEVICE" up

echo Output of wg show "$ZEROVPN_WIREGUARD_DEVICE":
wg show "$ZEROVPN_WIREGUARD_DEVICE"

echo Adding route...
ip route add "$ZEROVPN_NETWORK" dev "$ZEROVPN_WIREGUARD_DEVICE"

echo Setting up static leafs...
for leaf in $ZEROVPN_STATIC_CLIENTS; do
    echo "  Leaf: $leaf"
    leaf_private=$("$my_path"/0vpn-tool mixin "$ZEROVPN_KEYFILE" "$leaf")
  	leaf_public=$(echo "$leaf_private" | wg pubkey)
  	leaf_wg_ip=$("$my_path"/0vpn-resolve "$leaf")
    leaf_wg_ipv6="$("$my_path"/0vpn-ipv6-address "$ZEROVPN_KEYFILE" "$leaf")"
  
    echo "    $leaf public key: $leaf_public"
    echo "    $leaf VPN IP: $leaf_wg_ip"
  
  	wg set "$ZEROVPN_WIREGUARD_DEVICE" peer "$leaf_public" persistent-keepalive 10 allowed-ips "$leaf_wg_ip","$leaf_wg_ipv6"
  	# wg set $ZEROVPN_WIREGUARD_DEVICE peer $leaf_public persistent-keepalive 10 allowed-ips 10.0.0.0/8
  
    leaf_config="$TMPDIR"/configs/"$leaf".conf
  
    echo "    Creating config for static leaf $leaf_config..."
    {
        echo '[Interface]' 
        echo "PrivateKey = $leaf_private" 
        echo "Address = $leaf_wg_ip" 
        echo "DNS = $root_wg_ip, internal" 
        echo '[Peer]' 
        echo "PublicKey = $(wg pubkey < "$TMPFILE")" 
        echo "AllowedIps = 10.123.0.0/16" 
        echo "Endpoint = $ZEROVPN_SERVER_HOSTNAME:$ZEROVPN_WIREGUARD_PORT" 
        echo "PersistentKeepalive = 10" 
    } > "$leaf_config"
    echo "    Creating hosts entry..."
    {
      echo "$leaf_wg_ipv6" "$leaf.internal"
      echo "$leaf_wg_ip" "$leaf.internal"
    } > "$TMPDIR"/hosts/"$leaf"
done

echo Starting dnsmasq on port "$ZEROVPN_DNS_PORT"...
touch "$TMPDIR/dnsmasq.conf"
dnsmasq --pid-file="$TMPDIR/dnsmasq.pid" --no-hosts --addn-hosts="$TMPDIR/hosts" -p "$ZEROVPN_DNS_PORT" --conf-file="$TMPDIR"/dnsmasq.conf --log-facility=- --interface="$ZEROVPN_WIREGUARD_DEVICE"


echo Listening for dynamic nodes...
while true; do
  	"$my_path"/0vpn-handle-leaf-announcements "$ZEROVPN_WIREGUARD_DEVICE" "$ZEROVPN_KEYFILE" "$ZEROVPN_ANNOUNCE_PORT" "$TMPDIR"
	  sleep 10
done
