#!/bin/bash

set -e

keyfile="$1"
hostname="$2"

keyhash="$(sha256sum "$keyfile")"
hostnamehash="$(echo "$hostname" | sha256sum)"

echo fd"$(echo "$keyhash" | cut -c 1-2)"::"$(echo "$keyhash" | cut -c 3-4)""$(echo "$keyhash" | cut -c 5-6)"::"$(echo "$keyhash" | cut -c 7-8)""$(echo "$keyhash" | cut -c 9-10)"::"$(echo "$keyhash" | cut -c 11-12)""$(echo "$keyhash" | cut -c 13-14)"::"$(echo "$hostnamehash" | cut -c 1-2)""$(echo "$hostnamehash" | cut -c 3-4)"::"$(echo "$hostnamehash" | cut -c 5-6)""$(echo "$hostnamehash" | cut -c 7-8)"::"$(echo "$hostnamehash" | cut -c 9-10)""$(echo "$hostnamehash" | cut -c 11-12)"::"$(echo "$hostnamehash" | cut -c 13-14)""$(echo "$hostnamehash" | cut -c 15-16)"


