#!/bin/bash

set +e

my_path=$(dirname "$0")

device="$1"
keyfile="$2"
root_public_announce_port="$3"
tmpdir="$4"

IFS=' '

nc -ulkp "$root_public_announce_port" | while read -r line; do 
    # echo Got line: $line;
    read -ra tokens <<< "$line"
    # echo "  host: ${tokens[0]}  public: ${tokens[1]}"
    host=${tokens[0]}
    public=${tokens[1]}

    leaf_private=$("$my_path"/0vpn-tool mixin "$keyfile" "$host")
    # echo "    Private: $leaf_private"
    leaf_public=$(echo "$leaf_private" | wg pubkey)
    leaf_wg_ip=$("$my_path"/0vpn-resolve "$host")
    leaf_wg_ipv6="$("$my_path"/0vpn-ipv6-address "$keyfile" "$host")"
    # echo "    Public: $leaf_public  Leaf IP: $leaf_wg_ip"

    # echo "  Checking if they match:"
    if [ "$public" == "$leaf_public" ]; then 
        if [ ! -f "$tmpdir"/hosts/"$host" ]; then
            echo -e -n "\nMatch! adding the leaf: Host: $host  Public key: $leaf_public  IP: $leaf_wg_ip\n"
            wg set "$device" peer "$leaf_public" persistent-keepalive 10 allowed-ips "$leaf_wg_ip","$leaf_wg_ipv6"
            {
                echo "$leaf_wg_ipv6" "$host".internal
                echo "$leaf_wg_ip" "$host".internal
            } > "$tmpdir"/hosts/"$host"
            kill -1 $(cat "$tmpdir/dnsmasq.pid")
        fi
    else
        echo "  key mismatch. not adding leaf..."
    fi
done
