#!/bin/bash

set -e

my_path=$(dirname "$0")

device="$1"
keyfile="$2"
root_name="$3"
root_public_host="$4"
root_public_port="$5"
root_public_announce_port="$6"
announce_interval="$7"
leaf_name="$8"
dns_port="$9"

echo Creating temporary file...
TMPFILE=$(mktemp) || exit 1
echo tmpfile: "$TMPFILE"
trap 'echo Cleaning up...; rm -f "$TMPFILE"' EXIT

echo Setting up wireguard device "$device"...
echo Removing old device... $(ip link delete "$device")
ip link add "$device" type wireguard

leaf_ip=$("$my_path"/0vpn-resolve "$leaf_name")
echo Leaf VPN IP: "$leaf_ip"

ip addr add "$leaf_ip" dev "$device"
"$my_path"/0vpn-tool mixin "$keyfile" "$leaf_name" > "$TMPFILE"
wg set "$device" private-key "$TMPFILE"
ip link set "$device" up

rm -f "$TMPFILE"

echo Deriving root keys...

root_private=$("$my_path"/0vpn-tool mixin "$keyfile" "$root_name")
root_public=$(echo $root_private | wg pubkey)
root_ip=$("$my_path"/0vpn-resolve "$root_name")

echo Root public key: "$root_public"
echo Root VPN IP: "$root_ip"

echo Setting up root node endpoint...
wg set "$device" peer $root_public endpoint "$root_public_host":"$root_public_port" persistent-keepalive 10 allowed-ips 10.123.0.0/16

echo Output of wg show "$device":
wg show "$device"

echo Adding route...
ip route add 10.123.0.0/16 dev "$device"

# echo -e "search internal\\nnameserver $root_ip" | resolvconf -a "$device"
resolvectl dns "$device" "$root_ip":"$dns_port"
resolvectl domain "$device" internal


echo Entering leaf announcement loop...
while true; do 
	"$my_path"/0vpn-announce-leaf "$keyfile" "$leaf_name" "$root_public_host" "$root_public_announce_port" || echo Something went wrong announcing this leaf
	sleep "$announce_interval"
done
