#!/usr/bin/env bash

set -e

my_path=$(dirname "$0")

device="$1"
keyfile="$2"
root_name="$3"
root_public_host="$4"
root_public_port="$5"
root_public_announce_port="$6"
static_leafs="$7"

echo Creating temporary file...
TMPFILE=$(mktemp) || exit 1

echo TMPFILE is "$TMPFILE"

TMPDIR=$(mktemp -d) || exit 1

echo TMPDIR is "$TMPDIR"

mkdir "$TMPDIR/hosts"

chmod -R 755 "$TMPDIR"

trap 'kill $(cat "$TMPDIR/dnsmasq.pid"); rm -f "$TMPFILE"; rm -rf "$TMPDIR"' EXIT

root_wg_ip=$("$my_path"/0vpn_string_to_ip $root_name)
echo root wg ip: $root_wg_ip

mkdir -p "$my_path"/hosts
echo "$root_wg_ip" "$root_name".internal > "$my_path"/hosts/"$root_name"

echo Setting up wireguard device "$device"...
echo Deleting device...$(ip link delete $device)
ip link add $device type wireguard
ip addr add $root_wg_ip dev $device
"$my_path"/0vpn-tool mixin "$keyfile" $root_name > "$TMPFILE"

echo Root public key: $(cat "$TMPFILE" | wg pubkey)

wg set $device private-key "$TMPFILE"
wg set $device listen-port $root_public_port
ip link set $device up

echo Output of wg show "$device":
wg show "$device"

echo Adding route...
ip route add 10.123.0.0/16 dev wg0

echo Setting up static leafs...
for leaf in $static_leafs; do
    echo "  Leaf: $leaf"
	leaf_private=$("$my_path"/0vpn-tool mixin "$keyfile" $leaf)
	leaf_public=$(echo $leaf_private | wg pubkey)
	leaf_wg_ip=$("$my_path"/0vpn_string_to_ip "$leaf")

    echo "    $leaf public key: $leaf_public"
    echo "    $leaf VPN IP: $leaf_wg_ip"

	wg set $device peer $leaf_public persistent-keepalive 10 allowed-ips $leaf_wg_ip
	# wg set $device peer $leaf_public persistent-keepalive 10 allowed-ips 10.0.0.0/8

    leaf_config="$leaf"_leaf.cfg

    echo "    Creating config for static leaf $leaf_config..."
    echo '[Interface]' > "$leaf_config"
    echo "PrivateKey = $leaf_private" >> "$leaf_config"
    echo "Address = $leaf_wg_ip" >> "$leaf_config"
    echo "DNS = $root_wg_ip, internal" >> "$leaf_config"
    echo '[Peer]' >> "$leaf_config"
    echo "PublicKey = $(cat $TMPFILE | wg pubkey)" >> "$leaf_config"
    echo "AllowedIps = 10.123.0.0/16" >> "$leaf_config"
    echo "Endpoint = $root_public_host:$root_public_port" >> "$leaf_config"
    echo "PersistentKeepalive = 10" >> "$leaf_config"
    echo "    Creating hosts entry..."
    echo "$leaf_wg_ip" "$leaf.internal" > "$TMPDIR"/hosts/"$leaf"
done

echo Starting dnsmasq...
touch "$TMPDIR/dnsmasq.conf"
dnsmasq --pid-file="$TMPDIR/dnsmasq.pid" --no-hosts --addn-hosts="$TMPDIR/hosts" -p 53 --interface=wg0 -q --conf-file="$TMPDIR"/dnsmasq.conf --log-facility=- --interface=wg0 


echo Listening for dynamic nodes...
while true; do
	"$my_path"/0vpn_handle_leaf_announcements "$device" "$keyfile" "$root_public_announce_port" "$TMPDIR"
	sleep 10
done
