#!/usr/bin/env bash

set -e
# set -x

my_path=$(dirname "$0")

device="$1"
key="$2"
root_name="$3"
root_public_host="$4"
root_public_port="$5"
root_public_announce_port="$6"
announce_interval="$7"
leaf_name="$8"

echo Creating temporary file...
TMPFILE=$(mktemp) || exit 1

trap 'rm -f "$TMPFILE"' EXIT

echo Setting up wireguard device "$device"...
echo Removing old device... $(ip link delete "$device")
ip link add "$device" type wireguard

leaf_ip=$("$my_path"/0vpn_string_to_ip "$leaf_name")
echo Leaf VPN IP: "$leaf_ip"

ip addr add "$leaf_ip" dev "$device"
./0vpn-tool mixin "$key" "$leaf_name" > $TMPFILE
wg set "$device" private-key $TMPFILE
ip link set "$device" up

rm -f "$TMPFILE"

echo Deriving root keys...

root_private=$(./0vpn-tool mixin "$key" "$root_name")
root_public=$(echo $root_private | wg pubkey)
root_ip=$("$my_path"/0vpn_string_to_ip "$root_name")

echo Root public key: "$root_public"
echo Root VPN IP: "$root_ip"

echo Setting up root node endpoint...
wg set "$device" peer $root_public endpoint "$root_public_host":"$root_public_port" persistent-keepalive 10 allowed-ips 10.0.0.0/8

echo Output of wg show "$device":
wg show "$device"

echo Entering leaf announcement loop...
while true; do 
	"$my_path"/0vpn_announce_leaf "$key" "$1eaf_name" "$root_public_host" "$root_public_announce_port"
	sleep "$announce_interval"
done
