#!/usr/bin/env bash

set +e

my_path=$(dirname "$0")

if [ "$1" == mixin ]; then
	"$my_path"/0vpn-tool mixin "$2" "$3"
fi

if [ "$1" == resolve ]; then
	"$my_path"/0vpn_string_to_ip "$2" 
fi

if [ "$1" == root ]; then
	"$my_path"/0vpn_setup_root "$2"    "$3" "$4"        "$5"              "$6"              "$7"                       "$8"
    #                           device  key  root_name   root_public_host  root_public port  root_public_announce_port  static_leafs
fi

if [ "$1" == leaf ]; then
	"$my_path"/0vpn_setup_leaf "$2"    "$3" "$4"        "$5"              "$6"              "$7"                       "$8"              "$9"
    #                           device  key  root_name   root_public_host  root_public port  root_public_announce_port  annunce_interval  leaf_name
fi
