#!/bin/bash

set -e

my_path=$(dirname "$0")

keyfile="$1"
leaf_name="$2"
root_public_host="$3"
root_public_port="$4"

echo "$leaf_name" $(echo $("$my_path"/0vpn-tool mixin "$keyfile" "$leaf_name") | wg pubkey) > /dev/udp/"$root_public_host"/"$root_public_port"

