#!/usr/bin/env bash

set +x
set +e

my_path=$(dirname "$0")

device="$1"
keyfile="$2"
root_public_announce_port="$3"
tmpdir="$4"

IFS=' '

nc -ulkp "$root_public_announce_port" | while read line; do 
    echo Got line: $line;
    read -ra tokens <<< "$line"
    echo "  host: ${tokens[0]}"
    echo "  public: ${tokens[1]}"
    host=${tokens[0]}
    public=${tokens[1]}

    echo "  Rederiving leaf public key..."
    leaf_private=$("$my_path"/0vpn-tool mixin "$keyfile" "$host")
    # echo "    Private: $leaf_private"
    leaf_public=$(echo $leaf_private | wg pubkey)
    echo "    Public: $leaf_public"
    leaf_wg_ip=$("$my_path"/0vpn_string_to_ip "$host")
    echo "    Leaf IP: $leaf_wg_ip"

    echo "  Checking if they match:"
    if [ "${tokens[1]}" == "$leaf_public" ]; then 
        echo "  Match! adding the leaf..."
        wg set $device peer $leaf_public persistent-keepalive 10 allowed-ips $leaf_wg_ip
        echo "$leaf_wg_ip" "$host".internal > "$tmpdir"/hosts/"$host"
        kill -SIGHUP $(cat "$tmpdir/dnsmasq.pid")
    else
        echo "  key mismatch. not adding leaf..."
    fi
done
